media:
  folder: images
content:
  - name: setari
    label: Texte Site
    type: file
    file: content.json
    fields:
      - name: titlu
        label: Titlu Principal
        type: string
      - name: locuri
        label: Locuri Beta
        type: number